version: '3.5'

services:
  api1: &api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - HOST=db
    networks: 
      - mynet
  api2:
    <<: *api
    ports:
      - 8081:8080

  db:
    image: postgres:latest
    command: postgres -c max_connections=50 -c synchronous_commit='off' 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - 9999:9999
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - mynet
  

networks:
  mynet:
    driver: bridge

volumes:
  pgdata: