@RinhaAPI_HostAddress = http://localhost:5083

POST {{RinhaAPI_HostAddress}}/clientes/{id}/transacoes

Content-Type application/json 
{
    "clienteId": 2,
    "valor": 100,
    "tipo": "c",
    "descricao": "desc";
}
###
